// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtu7kBJmKNcoE2WQLZS4_E_jJW7610c-g',
    appId: '1:197427416717:web:ddb96aa9955e3955029cc4',
    messagingSenderId: '197427416717',
    projectId: 'login-system-772b8',
    authDomain: 'login-system-772b8.firebaseapp.com',
    storageBucket: 'login-system-772b8.appspot.com',
    measurementId: 'G-26FYWXLCZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdTVG1yY2PKz4laaaum_6OgFqzWfd5D8',
    appId: '1:197427416717:android:eae8f5be9e24b3b4029cc4',
    messagingSenderId: '197427416717',
    projectId: 'login-system-772b8',
    storageBucket: 'login-system-772b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfV_aeQDTyjFwPAbRe6-bQyT0RVvXVfM',
    appId: '1:197427416717:ios:e778491d11a94d22029cc4',
    messagingSenderId: '197427416717',
    projectId: 'login-system-772b8',
    storageBucket: 'login-system-772b8.appspot.com',
    iosBundleId: 'com.example.firebaseLoginsystem',
  );
}
